### ISSUE TITLE
Settings dialog won't open

### ISSUE THREAD

**Issue by TobiasPharos** [masqu3rad3/tik_manager4#70]
**Describe the bug**
Trying to open the settings dialog leads to an error.

**To Reproduce**
In menu bar click File > Settings

**Expected behavior**
Open a dialog

**DCC**
Tested in Standalone and Nuke

**Desktop (please complete the following information):**
 - Windows 10
 - Python 3.11.1
 - PySide2
 
**Additional context**
  File "C:\TikManager\tik_manager4-4.0.5-beta\tik_manager4\ui\main.py", line 498, in on_settings
    dialog = SettingsDialog(self.tik, parent=self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TikManager\tik_manager4-4.0.5-beta\tik_manager4\ui\dialog\settings_dialog.py", line 53, in __init__
    self.build_ui()
  File "C:\TikManager\tik_manager4-4.0.5-beta\tik_manager4\ui\dialog\settings_dialog.py", line 61, in build_ui
    self.build_static_widgets()
  File "C:\TikManager\tik_manager4-4.0.5-beta\tik_manager4\ui\dialog\settings_dialog.py", line 95, in build_static_widgets
    self.apply_button = tik_button_box.addButton("Apply", tik_button_box.ApplyRole)
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TikButtonBox' object has no attribute 'ApplyRole'

**Comment by masqu3rad3** [comment]
Hi, thank you for the bug report.

I couldn't replicate the issue on 
Nuke 13.2v2, 
Nuke 15.0v2 
standalone (using PyQt5 5.15.10)

Can you try the frozen standalone version (exe file) and let me know if that one works?
It is located in
tik_manager4\dist\tik4\tik4_standalone.exe

Thanks.

**Comment by TobiasPharos** [comment]
Hi Arda!
You're right, the frozen version works.

**Comment by masqu3rad3** [comment]
Thank you for confirming. It is still a mystery why its not working in Nuke though.

Which version of the Nuke you are trying?

**Comment by masqu3rad3** [comment]
Okay, I think I know the problem. I am getting the same error with pyside6 / PyQt6
I think you might be using a newer version of Nuke which is actually using pyside6.

I will resolve this issue and it will be updated with the next release.

**Comment by TobiasPharos** [comment]
Yes, I meanwhile came to the same result doing some PySide-Tests with the Standalone. It works with PyQt5 but not with PySide6.
The former tests were on Nuke 14.1v2. (but with pipeline tools creating an instance of PySide6)

**Comment by masqu3rad3** [comment]
Thanks for catching this Tobias, much appeciated.
I made a hotfix for and pushed to the master. Can you give it a try?

**Comment by TobiasPharos** [comment]
Yes, now it works in Standalone and (our) Nuke 14.1v2 with PySide6.
Thank you!

**Comment by masqu3rad3** [comment]
You are welcome, thanks for confirming.
